### ISSUE TITLE
can't find file 'slang'

### ISSUE THREAD

**Issue by zolomatok** [jeromegn/kilt#24]
👋

I'm trying to run a very simple Crystal/Kemal app, but upon building, I get the following error:
```
In lib/kilt/src/slang.cr:2:1
 2 | require "slang"
     ^
Error: can't find file 'slang'
```

The entire 'app':
```
require "./challenge/*"
require "kemal"
require "kilt/slang"


module Challenger
  
    get "/" do
        render "src/challenge/pages/home.slang", "src/challenge/pages/layouts/main.slang"
    end
    
    Kemal.config.port = 6969
    Kemal.run

end
```

shards.yml
```
name: challenger
version: 0.1.0
crystal: 0.35.1

targets:
    challenger:
        main: src/challenger.cr

dependencies:
    kemal:
        github: kemalcr/kemal
        branch: master
```

I did run `shards install`.
Can you please tell me what I'm doing wrong?

**Comment by jeromegn** [comment]
`kilt` provides an API on top of template engines. You'll have to add the slang shard to your project's dependencies:

```yaml
slang:
    github: jeromegn/slang
    branch: master
```
